### ISSUE TITLE
[バグ報告] 生徒用画面No.1

### ISSUE THREAD

**Issue by hiroka-sonobe-adglobe-co-jp** [yusui-okanaka-adglobe-co-jp/2023-Technical-Training-Team-C#32]
### 試験仕様書

https://docs.google.com/spreadsheets/d/1Z-zRKyTDX5zfkXhDFTNwtpGiYyadK5ZU/edit#gid=1720387801

### 試験No.

No.1

### 再現手順

```markdown
1.アドレスバーに以下を入力し、画面遷移をおこなう
http://localhost:3000/studentHome?date=2019-12-30
2.(8) 日付を確認する
```

### 期待結果

```markdown
(8) 日付が今週の日付になっている
```

### 不具合現象

```markdown
(8)日付が2019-12-30になっている
```

### 再現度

3/3

### 補足情報

```markdown
テスト設計書の記載に不足あり
テスト手順に「クエリパラメータなしで遷移する」と加筆が必要
```

**Comment by hiroka-sonobe-adglobe-co-jp** [comment]
設計書_生徒用画面のD11を修正しました。
https://docs.google.com/spreadsheets/d/1Z-zRKyTDX5zfkXhDFTNwtpGiYyadK5ZU/edit#gid=1720387801

**Comment by takayuki-miyazaki-adglobe-co-jp** [comment]
修正内容確認しました。
問題ありません。
