### ISSUE TITLE
[バグ報告] 登録画面試験外項目: 開始/終了日のフォーマットが設計書通りになっていない

### ISSUE THREAD

**Issue by takayuki-miyazaki-adglobe-co-jp** [yusui-okanaka-adglobe-co-jp/2023-Technical-Training-Team-C#61]
### 試験仕様書

https://docs.google.com/spreadsheets/d/1Z-zRKyTDX5zfkXhDFTNwtpGiYyadK5ZU/edit#gid=360017980

### 試験No.

試験外項目

### 再現手順

```markdown
1. 登録画面を表示する
2. (10) 開始日終了日ボタン を押下し、開始/終了日を設定する
3. (11) 開始日終了日表示 を確認する
```

### 期待結果

```markdown
- 日付のフォーマットが「yyyy/MM/dd」となっている
```

### 不具合現象

```markdown
- 日付のフォーマットが「yyyy-MM-dd」となっている
```

### 再現度

3/3

**Comment by yusui-okanaka-adglobe-co-jp** [comment]
画面設計書が間違っていたため、yyyy-MM-ddのフォーマットに修正しました。
https://docs.google.com/spreadsheets/d/1120AA1uF9_P03i_fM_-ZAqV515nW7sej/edit#gid=778773398

**Comment by shu-kimura-adglobe-co-jp** [comment]
修正されていることを確認いたしました
