### ISSUE TITLE
[バグ報告] 時間割取得API No.16

### ISSUE THREAD

**Issue by shu-kimura-adglobe-co-jp** [yusui-okanaka-adglobe-co-jp/2023-Technical-Training-Team-C#69]
### 試験仕様書

https://docs.google.com/spreadsheets/d/1bioi-yrjzQQ-EMAoC6yUJckjkaDIrNwR/edit#gid=802882450

### 試験No.

No.16

### 再現手順

```markdown
時間割取得API_パターン No.16 のリクエストを送信する
```

### 期待結果

```markdown
時間割取得API_パターン No.16 のレスポンスが受信される
```

### 不具合現象

```markdown
異なるレスポンスが返ってくる

時間割取得API_パターン No.15 などのレスポンスと同じ
```

### 再現度

3/3

**Comment by hiroka-sonobe-adglobe-co-jp** [comment]
テスト設計書(バックエンド)_時間割取得API_パターンのB17を修正しました。
https://docs.google.com/spreadsheets/d/1bioi-yrjzQQ-EMAoC6yUJckjkaDIrNwR/edit#gid=1347369974

**Comment by shu-kimura-adglobe-co-jp** [comment]
修正されていることを確認いたしました
