### ISSUE TITLE
[バグ報告] 一覧画面　試験外項目3

### ISSUE THREAD

**Issue by hiroka-sonobe-adglobe-co-jp** [yusui-okanaka-adglobe-co-jp/2023-Technical-Training-Team-C#70]
### 試験仕様書

https://docs.google.com/spreadsheets/d/1Z-zRKyTDX5zfkXhDFTNwtpGiYyadK5ZU/edit#gid=1720387801

### 試験No.

試験外項目

### 再現手順

```markdown
1.一覧画面に遷移
```

### 期待結果

```markdown
設計書通りのデザイン
```

### 不具合現象

```markdown
ボタンの位置がずれている
```

### 再現度

3/3

### 補足情報

```markdown
marginの設定ミスだと思われます。
```

**Comment by shu-kimura-adglobe-co-jp** [comment]
修正されていることを確認いたしました
